FROM node:20-alpine
WORKDIR /app
RUN corepack enable
COPY package.json pnpm-workspace.yaml tsconfig.base.json ./
COPY apps/scheduler/package.json apps/scheduler/package.json
COPY packages/shared/package.json packages/shared/package.json
RUN pnpm install --filter @mobspecs/scheduler... --frozen-lockfile=false
COPY . .
CMD ["pnpm", "--filter", "@mobspecs/scheduler", "dev"]
